// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAftdWeGNrkjWPNM9AWHm-we1HvlJKAXgg',
    appId: '1:230154274088:web:bf9decf34064ad99ff7c1d',
    messagingSenderId: '230154274088',
    projectId: 'carpolfyp',
    authDomain: 'carpolfyp.firebaseapp.com',
    databaseURL: 'https://carpolfyp-default-rtdb.firebaseio.com',
    storageBucket: 'carpolfyp.appspot.com',
    measurementId: 'G-11DBH1ECXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCvocQWkqjltHuYc3zZtVGx6LyBnlEH-g',
    appId: '1:230154274088:android:6bc86208cc4875eaff7c1d',
    messagingSenderId: '230154274088',
    projectId: 'carpolfyp',
    databaseURL: 'https://carpolfyp-default-rtdb.firebaseio.com',
    storageBucket: 'carpolfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdS7mCZbwhegPY_hP0P2v8z_RCy6nra1I',
    appId: '1:230154274088:ios:dba02bbb86e82c2fff7c1d',
    messagingSenderId: '230154274088',
    projectId: 'carpolfyp',
    databaseURL: 'https://carpolfyp-default-rtdb.firebaseio.com',
    storageBucket: 'carpolfyp.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
